[tool.poetry]
name = "calc"
version = "0.1.0"
description = ""
authors = ["Tarcisio Eduardo Moreira Crocomo <tarcisio.crocomo@gmail.com>"]

[tool.poetry.dependencies]
python = "*"
flask = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
