DEFAULT_X_MAX = 630
DEFAULT_X_MIN = 0
DEFAULT_Y_MAX = 380
DEFAULT_Y_MIN = 0

X_MAX_TRANSLATED = DEFAULT_X_MAX / 2
X_MIN_TRANSLATED = -DEFAULT_X_MAX / 2
Y_MAX_TRANSLATED = DEFAULT_Y_MAX / 2
Y_MIN_TRANSLATED = -DEFAULT_Y_MAX / 2

MIN_NORMALIZED_VALUE = -1
MAX_NORMALIZED_VALUE = 1

SHIFT_FACTOR = 1e-3
