#include <architecture/ia32/ia32_pmu.h>

__BEGIN_SYS


const Intel_Sandy_Bridge_PMU::Event Intel_Sandy_Bridge_PMU::_events[Intel_Sandy_Bridge_PMU::EVENTS] = {
    // Architecture                              // NUM
    Intel_Sandy_Bridge_PMU::Intel_Sandy_Bridge_PMU::INSTRUCTIONS_RETIRED,                        // 000
    Intel_Sandy_Bridge_PMU::UNHALTED_REFERENCE_CYCLES,                   // 001
    Intel_Sandy_Bridge_PMU::UNHALTED_CORE_CYCLES,                        // 002
    Intel_Sandy_Bridge_PMU::BRANCH_INSTRUCTIONS_RETIRED,                 // 003
    Intel_Sandy_Bridge_PMU::BRANCH_MISSES_RETIRED,                       // 004
    Intel_Sandy_Bridge_PMU::MEM_LOAD_UOPS_RETIRED_L1_HIT,                // 005
    Intel_Sandy_Bridge_PMU::MEM_LOAD_UOPS_RETIRED_L2_HIT,                // 006
    Intel_Sandy_Bridge_PMU::LLC_REFERENCES,                              // 007
    Intel_Sandy_Bridge_PMU::LLC_MISSES,                                  // 008
    Intel_Sandy_Bridge_PMU::ICACHE_MISSES,                               // 009
    Intel_Sandy_Bridge_PMU::OTHER_ASSISTS_ITLB_MISS_RETIRED,             // 010
    Intel_Sandy_Bridge_PMU::BR_INST_EXEC_COND,                           // 011
    Intel_Sandy_Bridge_PMU::L2_TRANS_L1D_WB,                             // 012
    Intel_Sandy_Bridge_PMU::L2_TRANS_L2_WB,                              // 013
    Intel_Sandy_Bridge_PMU::MEM_UOP_RETIRED_ALL,                         // 014
    Intel_Sandy_Bridge_PMU::L1D_EVICTION,                                // 015
    Intel_Sandy_Bridge_PMU::IDQ_UOPS_NOT_DELIVERED_CORE,                 // 016
    Intel_Sandy_Bridge_PMU::IDQ_EMPTY,                                   // 017
    Intel_Sandy_Bridge_PMU::BR_MISP_EXEC_RETURN_NEAR,                    // 018
    Intel_Sandy_Bridge_PMU::FP_COMP_OPS_EXE_X87,                         // 019
    Intel_Sandy_Bridge_PMU::DTLB_STORE_MISSES_WALK_DURATION,             // 020
    Intel_Sandy_Bridge_PMU::DTLB_LOAD_MISSES_MISS_WALK_DURATION,         // 021
    Intel_Sandy_Bridge_PMU::BR_INST_EXEC_RETURN_NEAR,                    // 022
    Intel_Sandy_Bridge_PMU::RESOURCE_STALLS_SB,                          // 023
    Intel_Sandy_Bridge_PMU::XSNP_HIT,                                    // 024
    Intel_Sandy_Bridge_PMU::BR_MISP_EXEC_INDIRECT_JMP_NON_CALL_RET,      // 025
    Intel_Sandy_Bridge_PMU::BR_MISP_RETIRED_CONDITIONAL,                 // 026
    Intel_Sandy_Bridge_PMU::LD_BLOCKS_DATA_UNKNOWN,                      // 027
    Intel_Sandy_Bridge_PMU::LD_BLOCKS_STORE_FORWARD,                     // 028
    Intel_Sandy_Bridge_PMU::LD_BLOCKS_NO_SR,                             // 029
    Intel_Sandy_Bridge_PMU::LD_BLOCKS_ALL_BLOCK,                         // 030
    Intel_Sandy_Bridge_PMU::MISALIGN_MEM_REF_LOADS,                      // 031
    Intel_Sandy_Bridge_PMU::MISALIGN_MEM_REF_STORES,                     // 032
    Intel_Sandy_Bridge_PMU::LD_BLOCKS_PARTIAL_ADDRESS_ALIAS,             // 033
    Intel_Sandy_Bridge_PMU::LD_BLOCKS_PARTIAL_ALL_STA_BLCOK,             // 034
    Intel_Sandy_Bridge_PMU::DTLB_LOAD_MISSES_MISS_CAUSES_A_WALK,         // 035
    Intel_Sandy_Bridge_PMU::DTLB_LOAD_MISSES_MISS_WALK_COMPLETED,        // 036
    Intel_Sandy_Bridge_PMU::DTLB_LOAD_MISSES_MISS_STLB_HIT,              // 037
    Intel_Sandy_Bridge_PMU::INT_MISC_RECOVERY_CYCLES,                    // 038
    Intel_Sandy_Bridge_PMU::INT_MISC_RAT_STALL_CYCLES,                   // 039
    Intel_Sandy_Bridge_PMU::UOPS_ISSUED_ANY,                             // 040
    Intel_Sandy_Bridge_PMU::FP_COMP_OPS_EXE_SSE_FP_PACKED_DOUBLE,        // 041
    Intel_Sandy_Bridge_PMU::FP_COMP_OPS_EXE_SSE_FP_SCALAR_SINGLE,        // 042
    Intel_Sandy_Bridge_PMU::FP_COMP_OPS_EXE_SSE_PACKED_SINGLE,           // 043
    Intel_Sandy_Bridge_PMU::FP_COMP_OPS_EXE_SSE_SCALAR_DOUBLE,           // 044
    Intel_Sandy_Bridge_PMU::SIMD_FP_256_PACKED_SINGLE,                   // 045
    Intel_Sandy_Bridge_PMU::SIMD_FP_256_PACKED_DOUBLE,                   // 046
    Intel_Sandy_Bridge_PMU::ARITH_FPU_DIV_ACTIVE,                        // 047
    Intel_Sandy_Bridge_PMU::INSTS_WRITTEN_TO_IQ_INSTS,                   // 048
    Intel_Sandy_Bridge_PMU::L2_RQSTS_DEMAND_DATA_RD_HIT,                 // 049
    Intel_Sandy_Bridge_PMU::L2_RQSTS_ALL_DEMAND_DATA_RD,                 // 050
    Intel_Sandy_Bridge_PMU::L2_RQSTS_RFO_HITS,                           // 051
    Intel_Sandy_Bridge_PMU::L2_RQSTS_RFO_MISS,                           // 052
    Intel_Sandy_Bridge_PMU::L2_RQSTS_ALL_RFO,                            // 053
    Intel_Sandy_Bridge_PMU::L2_RQSTS_CODE_RD_HIT,                        // 054
    Intel_Sandy_Bridge_PMU::L2_RQSTS_CODE_RD_MISS,                       // 055
    Intel_Sandy_Bridge_PMU::L2_RQSTS_ALL_CODE_RD,                        // 056
    Intel_Sandy_Bridge_PMU::L2_RQSTS_PF_HIT,                             // 057
    Intel_Sandy_Bridge_PMU::L2_RQSTS_PF_MISS,                            // 058
    Intel_Sandy_Bridge_PMU::L2_RQSTS_ALL_PF,                             // 059
    Intel_Sandy_Bridge_PMU::L2_STORE_LOCK_RQSTS_MISS,                    // 060
    Intel_Sandy_Bridge_PMU::L2_STORE_LOCK_RQSTS_HIT_E,                   // 061
    Intel_Sandy_Bridge_PMU::L2_STORE_LOCK_RQSTS_HIT_M,                   // 062
    Intel_Sandy_Bridge_PMU::L2_STORE_LOCK_RQSTS_ALL,                     // 063
    Intel_Sandy_Bridge_PMU::L2_L1D_WB_RQSTS_HIT_E,                       // 064
    Intel_Sandy_Bridge_PMU::L2_L1D_WB_RQSTS_HIT_M,                       // 065
    Intel_Sandy_Bridge_PMU::L2_TRANS_DEMAND_DATA_RD,                     // 066
    Intel_Sandy_Bridge_PMU::L2_TRANS_RFO,                                // 067
    Intel_Sandy_Bridge_PMU::L2_TRANS_CODE_RD,                            // 068
    Intel_Sandy_Bridge_PMU::L2_TRANS_ALL_PF,                             // 069
    Intel_Sandy_Bridge_PMU::L2_TRANS_L2_FILL,                            // 070
    Intel_Sandy_Bridge_PMU::L2_TRANS_ALL_REQ_UESTS,                      // 071
    Intel_Sandy_Bridge_PMU::L2_LINES_IN_I,                               // 072
    Intel_Sandy_Bridge_PMU::L2_LINES_IN_S,                               // 073
    Intel_Sandy_Bridge_PMU::L2_LINES_IN_E,                               // 074
    Intel_Sandy_Bridge_PMU::L2_LINES_IN_ALL,                             // 075
    Intel_Sandy_Bridge_PMU::L2_LINES_OUT_DEMAND_CLEAN,                   // 076
    Intel_Sandy_Bridge_PMU::L2_LINES_OUT_DEMAND_DIRTY,                   // 077
    Intel_Sandy_Bridge_PMU::L2_LINES_OUT_DEMAND_PF_CLEAN,                // 078
    Intel_Sandy_Bridge_PMU::L2_LINES_OUT_DEMAND_PF_DIRTY,                // 079
    Intel_Sandy_Bridge_PMU::L2_LINES_OUT_DEMAND_DIRTY_ALL,               // 080
    Intel_Sandy_Bridge_PMU::LONGEST_LAT_CACHE_REFERENCE,                 // 081
    Intel_Sandy_Bridge_PMU::LONGEST_LAT_CACHE_MISS,                      // 082
    Intel_Sandy_Bridge_PMU::CPU_CLK_UNHALTED_THREAD_P,                   // 083
    Intel_Sandy_Bridge_PMU::CPU_CLK_THREAD_UNHALTED_REF_XCLK,            // 084
    Intel_Sandy_Bridge_PMU::L1D_PEND_MISS_PENDING,                       // 085
    Intel_Sandy_Bridge_PMU::DTLB_STORE_MISSES_MISS_CAUSES_A_WALK,        // 086
    Intel_Sandy_Bridge_PMU::DTLB_STORE_MISSES_WALK_COMPLETED,            // 087
    Intel_Sandy_Bridge_PMU::DTLB_STORE_MISSES_TLB_HIT,                   // 088
    Intel_Sandy_Bridge_PMU::LOAD_HIT_PRE_SW_PF,                          // 089
    Intel_Sandy_Bridge_PMU::LOAD_HIT_PREHW_PF,                           // 090
    Intel_Sandy_Bridge_PMU::HW_PRE_REQ_DL1_MISS,                         // 091
    Intel_Sandy_Bridge_PMU::L1D_REPLACEMENT,                             // 092
    Intel_Sandy_Bridge_PMU::L1D_ALLOCATED_IN_M,                          // 093
    Intel_Sandy_Bridge_PMU::L1D_ALL_M_REPLACEMENT,                       // 094
    Intel_Sandy_Bridge_PMU::PARTIAL_RAT_STALLS_FLAGS_MERGE_UOP,          // 095
    Intel_Sandy_Bridge_PMU::PARTIAL_RAT_STALLS_SLOW_LEA_WINDOW,          // 096
    Intel_Sandy_Bridge_PMU::PARTIAL_RAT_STALLS_MUL_SINGLE_UOP,           // 097
    Intel_Sandy_Bridge_PMU::RESOURCE_STALLS2_ALL_FL_EMPTY,               // 098
    Intel_Sandy_Bridge_PMU::RESOURCE_STALLS2_ALL_PRF_CONTROL,            // 099
    Intel_Sandy_Bridge_PMU::RESOURCE_STALLS2_BOB_FULL,                   // 100
    Intel_Sandy_Bridge_PMU::RESOURCE_STALLS2_OOO_RSRC,                   // 101
    Intel_Sandy_Bridge_PMU::CPL_CYCLES_RING0,                            // 102
    Intel_Sandy_Bridge_PMU::CPL_CYCLES_RING123,                          // 103
    Intel_Sandy_Bridge_PMU::RS_EVENTS_EMPTY_CYCLES,                      // 104
    Intel_Sandy_Bridge_PMU::OFFCORE_REQUESTS_OUTSTANDING_DEMAND_DATA_RD, // 105
    Intel_Sandy_Bridge_PMU::OFFCORE_REQUESTS_OUTSTANDING_DEMAND_RFO,     // 106
    Intel_Sandy_Bridge_PMU::OFFCORE_REQUESTS_OUTSTANDING_ALL_DATA_RD,    // 107
    Intel_Sandy_Bridge_PMU::LOCK_CYCLES_SPLIT_LOCK_UC_LOCK_DURATION,     // 108
    Intel_Sandy_Bridge_PMU::LOCK_CYCLES_CACHE_LOCK_DURATION,             // 109
    Intel_Sandy_Bridge_PMU::IDQ_MITE_UOPS,                               // 110
    Intel_Sandy_Bridge_PMU::IDQ_DSB_UOPS,                                // 111
    Intel_Sandy_Bridge_PMU::IDQ_MS_DSB_UOPS,                             // 112
    Intel_Sandy_Bridge_PMU::IDQ_MS_MITE_UOPS,                            // 113
    Intel_Sandy_Bridge_PMU::IDQ_MS_UOPS,                                 // 114
    Intel_Sandy_Bridge_PMU::ITLB_MISSES_MISS_CAUSES_A_WALK,              // 115
    Intel_Sandy_Bridge_PMU::ITLB_MISSES_WALK_COMPLETED,                  // 116
    Intel_Sandy_Bridge_PMU::ITLB_MISSES_WALK_DURATION,                   // 117
    Intel_Sandy_Bridge_PMU::ITLB_MISSES_STLB_HIT,                        // 118
    Intel_Sandy_Bridge_PMU::ILD_STALL_LCP,                               // 119
    Intel_Sandy_Bridge_PMU::ILD_STALL_IQ_FULL,                           // 120
    Intel_Sandy_Bridge_PMU::BR_INST_EXEC_DIRECT_JMP,                     // 121
    Intel_Sandy_Bridge_PMU::BR_INST_EXEC_INDIRECT_JMP_NON_CALL_RET,      // 122
    Intel_Sandy_Bridge_PMU::BR_INST_EXEC_DIRECT_NEAR_CALL,               // 123
    Intel_Sandy_Bridge_PMU::BR_INST_EXEC_INDIRECT_NEAR_CALL,             // 124
    Intel_Sandy_Bridge_PMU::BR_INST_EXEC_NON_TAKEN,                      // 125
    Intel_Sandy_Bridge_PMU::BR_INST_EXEC_TAKEN,                          // 126
    Intel_Sandy_Bridge_PMU::BR_INST_EXEC_ALL_BRANCHES,                   // 127
    Intel_Sandy_Bridge_PMU::BR_MISP_EXEC_COND,                           // 128
    Intel_Sandy_Bridge_PMU::BR_MISP_EXEC_DIRECT_NEAR_CALL,               // 129
    Intel_Sandy_Bridge_PMU::BR_MISP_EXEC_INDIRECT_NEAR_CALL,             // 130
    Intel_Sandy_Bridge_PMU::BR_MISP_EXEC_NON_TAKEN,                      // 131
    Intel_Sandy_Bridge_PMU::BR_MISP_EXEC_TAKEN,                          // 132
    Intel_Sandy_Bridge_PMU::BR_MISP_EXEC_ALL_BRANCHES,                   // 133
    Intel_Sandy_Bridge_PMU::UOPS_DISPATCHED_PORT_PORT_0,                 // 134
    Intel_Sandy_Bridge_PMU::UOPS_DISPATCHED_PORT_PORT_1,                 // 135
    Intel_Sandy_Bridge_PMU::UOPS_DISPATCHED_PORT_PORT_2_LD,              // 136
    Intel_Sandy_Bridge_PMU::UOPS_DISPATCHED_PORT_PORT_2_STA,             // 137
    Intel_Sandy_Bridge_PMU::UOPS_DISPATCHED_PORT_PORT_2,                 // 138
    Intel_Sandy_Bridge_PMU::UOPS_DISPATCHED_PORT_PORT_3_LD,              // 139
    Intel_Sandy_Bridge_PMU::UOPS_DISPATCHED_PORT_PORT_3_STA,             // 140
    Intel_Sandy_Bridge_PMU::UOPS_DISPATCHED_PORT_PORT_3,                 // 141
    Intel_Sandy_Bridge_PMU::UOPS_DISPATCHED_PORT_PORT_4,                 // 142
    Intel_Sandy_Bridge_PMU::UOPS_DISPATCHED_PORT_PORT_5,                 // 143
    Intel_Sandy_Bridge_PMU::RESOURCE_STALLS_ANY,                         // 144
    Intel_Sandy_Bridge_PMU::RESOURCE_STALLS_LB,                          // 145
    Intel_Sandy_Bridge_PMU::RESOURCE_STALLS_RS,                          // 146
    Intel_Sandy_Bridge_PMU::RESOURCE_STALLS_ROB,                         // 147
    Intel_Sandy_Bridge_PMU::RESOURCE_STALLS_FCSW,                        // 148
    Intel_Sandy_Bridge_PMU::RESOURCE_STALLS_MXCSR,                       // 149
    Intel_Sandy_Bridge_PMU::RESOURCE_STALLS_OTHER,                       // 150
    Intel_Sandy_Bridge_PMU::DSB2MITE_SWITCHES_COUNT,                     // 151
    Intel_Sandy_Bridge_PMU::DSB2MITE_SWITCHES_PENALTY_CYCLES,            // 152
    Intel_Sandy_Bridge_PMU::DSB_FILL_OTHER_CANCEL,                       // 153
    Intel_Sandy_Bridge_PMU::DSB_FILL_EXCEED_DSB_LINES,                   // 154
    Intel_Sandy_Bridge_PMU::DSB_FILL_ALL_CANCEL,                         // 155
    Intel_Sandy_Bridge_PMU::ITLB_ITLB_FLUSH,                             // 156
    Intel_Sandy_Bridge_PMU::OFFCORE_REQUESTS_DEMAND_DATA_RD,             // 157
    Intel_Sandy_Bridge_PMU::OFFCORE_REQUESTS_DEMAND_RFO,                 // 158
    Intel_Sandy_Bridge_PMU::OFFCORE_REQUESTS_ALL_DATA_RD,                // 159
    Intel_Sandy_Bridge_PMU::UOPS_DISPATCHED_THREAD,                      // 160
    Intel_Sandy_Bridge_PMU::UOPS_DISPATCHED_CORE,                        // 161
    Intel_Sandy_Bridge_PMU::OFFCORE_REQUESTS_BUFFER_SQ_FULL,             // 162
    Intel_Sandy_Bridge_PMU::AGU_BYPASS_CANCEL_COUNT,                     // 163
    Intel_Sandy_Bridge_PMU::OFF_CORE_RESPONSE_0,                         // 164
    Intel_Sandy_Bridge_PMU::OFF_CORE_RESPONSE_1,                         // 165
    Intel_Sandy_Bridge_PMU::TLB_FLUSH_DTLB_THREAD,                       // 166
    Intel_Sandy_Bridge_PMU::TLB_FLUSH_STLB_ANY,                          // 167
    Intel_Sandy_Bridge_PMU::L1D_BLOCKS_BANK_CONFLICT_CYCLES,             // 168
    Intel_Sandy_Bridge_PMU::INST_RETIRED_ANY_P,                          // 169
    Intel_Sandy_Bridge_PMU::INST_RETIRED_PREC_DIST,                      // 170
    Intel_Sandy_Bridge_PMU::OTHER_ASSISTS_AVX_STORE,                     // 171
    Intel_Sandy_Bridge_PMU::OTHER_ASSISTS_AVX_TO_SSE,                    // 172
    Intel_Sandy_Bridge_PMU::OTHER_ASSISTS_SSE_TO_AVX,                    // 173
    Intel_Sandy_Bridge_PMU::UOPS_RETIRED_ALL,                            // 174
    Intel_Sandy_Bridge_PMU::UOPS_RETIRED_RETIRE_SLOTS,                   // 175
    Intel_Sandy_Bridge_PMU::MACHINE_CLEARS_MEMORY_ORDERING,              // 176
    Intel_Sandy_Bridge_PMU::MACHINE_CLEARS_SMC,                          // 177
    Intel_Sandy_Bridge_PMU::MACHINE_CLEARS_MASKMOV,                      // 178
    Intel_Sandy_Bridge_PMU::BR_INST_RETIRED_ALL_BRANCHES_ARCH,           // 179
    Intel_Sandy_Bridge_PMU::BR_INST_RETIRED_CONDITIONAL,                 // 180
    Intel_Sandy_Bridge_PMU::BR_INST_RETIRED_NEAR_CALL,                   // 181
    Intel_Sandy_Bridge_PMU::BR_INST_RETIRED_ALL_BRANCHES,                // 182
    Intel_Sandy_Bridge_PMU::BR_INST_RETIRED_NEAR_RETURN,                 // 183
    Intel_Sandy_Bridge_PMU::BR_INST_RETIRED_NOT_TAKEN,                   // 184
    Intel_Sandy_Bridge_PMU::BR_INST_RETIRED_NEAR_TAKEN,                  // 185
    Intel_Sandy_Bridge_PMU::BR_INST_RETIRED_FAR_BRANCH,                  // 186
    Intel_Sandy_Bridge_PMU::BR_MISP_RETIRED_ALL_BRANCHES_ARCH,           // 187
    Intel_Sandy_Bridge_PMU::BR_MISP_RETIRED_NEAR_CALL,                   // 188
    Intel_Sandy_Bridge_PMU::BR_MISP_RETIRED_ALL_BRANCHES,                // 189
    Intel_Sandy_Bridge_PMU::BR_MISP_RETIRED_NOT_TAKEN,                   // 190
    Intel_Sandy_Bridge_PMU::BR_MISP_RETIRED_TAKEN,                       // 191
    Intel_Sandy_Bridge_PMU::FP_ASSIST_X87_OUTPUT,                        // 192
    Intel_Sandy_Bridge_PMU::FP_ASSIST_X87_INPUT,                         // 193
    Intel_Sandy_Bridge_PMU::FP_ASSIST_SIMD_OUTPUT,                       // 194
    Intel_Sandy_Bridge_PMU::FP_ASSIST_SIMD_INPUT,                        // 195
    Intel_Sandy_Bridge_PMU::FP_ASSIST_ANY,                               // 196
    Intel_Sandy_Bridge_PMU::ROB_MISC_EVENTS_LBR_INSERTS,                 // 197
    Intel_Sandy_Bridge_PMU::MEM_TRANS_RETIRED_LOAD_LATENCY,              // 198
    Intel_Sandy_Bridge_PMU::MEM_TRANS_RETIRED_PRECISE_STORE,             // 199
    Intel_Sandy_Bridge_PMU::MEM_UOP_RETIRED_LOADS,                       // 200
    Intel_Sandy_Bridge_PMU::MEM_UOP_RETIRED_STORES,                      // 201
    Intel_Sandy_Bridge_PMU::MEM_UOP_RETIRED_STLB_MISS,                   // 202
    Intel_Sandy_Bridge_PMU::MEM_UOP_RETIRED_LOCK,                        // 203
    Intel_Sandy_Bridge_PMU::MEM_UOP_RETIRED_SPLIT,                       // 204
    Intel_Sandy_Bridge_PMU::MEM_UOPS_RETIRED_ALL_LOADS,                  // 205
    Intel_Sandy_Bridge_PMU::MEM_LOAD_UOPS_RETIRED_L3_HIT,                // 206
    Intel_Sandy_Bridge_PMU::MEM_LOAD_UOPS_RETIRED_HIT_LFB,               // 207
    Intel_Sandy_Bridge_PMU::XSNP_MISS,                                   // 208
    Intel_Sandy_Bridge_PMU::XSNP_HITM,                                   // 209
    Intel_Sandy_Bridge_PMU::XSNP_NONE,                                   // 210
    Intel_Sandy_Bridge_PMU::MEM_LOAD_UOPS_MISC_RETIRED_LLC_MISS,         // 211
    Intel_Sandy_Bridge_PMU::SQ_MISC_SPLIT_LOCK                           // 212
};


__END_SYS
